import { useEffect, useState } from 'react'
import { Pencil, Plus, Save, Trash2, X } from 'lucide-react'
import { PRICE_TABLE } from '../../data/seeds'
import { useAuth } from '../../context/AuthContext'
import { useUI } from '../../context/UIContext'
import { ensurePriceTable, savePriceTable, subscribePriceTable } from '../../services/firestore'

const money=(v)=>Number(v||0).toLocaleString('pt-BR')
const clone=(v)=>JSON.parse(JSON.stringify(v))
const keyFromLabel=(label)=>`${label.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')}_${Date.now()}`

export default function PricesPage(){
 const {canEditPrices}=useAuth();const{toast,confirm}=useUI()
 const[prices,setPrices]=useState(()=>clone(PRICE_TABLE));const[draft,setDraft]=useState(()=>clone(PRICE_TABLE));const[editing,setEditing]=useState(false);const[saving,setSaving]=useState(false)
 const[newService,setNewService]=useState({label:'',price:'',max:'',durability:''})

 useEffect(()=>subscribePriceTable((table,exists)=>{setPrices(clone(table));if(!editing)setDraft(clone(table));if(!exists&&canEditPrices)ensurePriceTable().catch(console.error)},(error)=>{console.error(error);toast('Não foi possível carregar a tabela de preços.','error')}),[canEditPrices,editing,toast])

 const setNumber=(path,value)=>{const next=clone(draft);let cursor=next;for(let i=0;i<path.length-1;i++)cursor=cursor[path[i]];cursor[path.at(-1)]=Math.max(0,Number(value)||0);setDraft(next)}
 const startEdit=()=>{setDraft(clone(prices));setEditing(true)}
 const cancel=()=>{setDraft(clone(prices));setNewService({label:'',price:'',max:'',durability:''});setEditing(false)}
 const save=async()=>{try{setSaving(true);await savePriceTable(draft);setEditing(false);toast('Tabela de preços atualizada para toda a equipe. A calculadora já usa os novos valores.','success')}catch(error){console.error(error);toast('Não foi possível salvar a tabela de preços.','error')}finally{setSaving(false)}}
 const addService=()=>{if(!newService.label.trim()||!Number(newService.price))return toast('Informe o nome e o valor do novo serviço.','warning');const item={key:keyFromLabel(newService.label),label:newService.label.trim(),price:Number(newService.price)};if(Number(newService.max))item.max=Number(newService.max);if(Number(newService.durability))item.durability=Number(newService.durability);setDraft({...draft,items:[...draft.items,item]});setNewService({label:'',price:'',max:'',durability:''});toast('Novo tipo de serviço adicionado à edição. Salve a tabela para aplicar.','info')}
 const removeService=async(key)=>{const ok=await confirm({title:'Remover serviço',message:'Este tipo de serviço deixará de aparecer na tabela e na calculadora após salvar as alterações.',danger:true,confirmLabel:'Remover'});if(ok)setDraft({...draft,items:draft.items.filter(i=>i.key!==key)})}
 const view=editing?draft:prices

 return <>
  <div className="page-heading"><div><span className="eyebrow">REFERÊNCIA</span><h1>Tabela de preços</h1><p>Valores sincronizados pelo Firebase e usados automaticamente na calculadora.</p></div>{canEditPrices&&!editing&&<button className="button primary" onClick={startEdit}><Pencil size={17}/> Editar tabela</button>}{canEditPrices&&editing&&<div className="page-actions"><button className="button ghost" onClick={cancel}><X size={17}/> Cancelar</button><button className="button primary" onClick={save} disabled={saving}><Save size={17}/> {saving?'Salvando...':'Salvar alterações'}</button></div>}</div>
  {editing&&<div className="alert info price-edit-note">Modo de edição ativo. Alterações entram na calculadora de todos os usuários após clicar em <strong>Salvar alterações</strong>.</div>}
  <div className="card"><div className="table-scroll"><table><thead><tr><th>Tuning</th><th>Nível 1</th><th>Nível 2</th><th>Nível 3</th><th>Nível 4</th><th>Nível 5</th><th>Full</th></tr></thead><tbody>{Object.entries(view.tuning||{}).map(([name,levels])=><tr key={name}><td><strong>{name}</strong></td>{[0,1,2,3,4].map(i=><td key={i}>{levels[i]!==undefined?(editing?<input className="price-input" type="number" min="0" value={levels[i]} onChange={e=>setNumber(['tuning',name,i],e.target.value)}/>:money(levels[i])):'—'}</td>)}<td>—</td></tr>)}<tr className="highlight-row"><td><strong>FULL TUNING</strong></td><td colSpan="5"></td><td>{editing?<input className="price-input" type="number" min="0" value={view.fullTuning} onChange={e=>setNumber(['fullTuning'],e.target.value)}/>:<strong>{money(view.fullTuning)}</strong>}</td></tr><tr><td><strong>Blindagem</strong></td>{[0,1,2,3,4].map(i=><td key={i}>{editing?<input className="price-input" type="number" min="0" value={view.blindagem?.[i]||0} onChange={e=>setNumber(['blindagem',i],e.target.value)}/>:money(view.blindagem?.[i])}</td>)}<td>{editing?<input className="price-input" type="number" min="0" value={view.fullBlindagem} onChange={e=>setNumber(['fullBlindagem'],e.target.value)}/>:<strong>{money(view.fullBlindagem)}</strong>}</td></tr></tbody></table></div></div>
  <div className="content-grid two top-gap"><div className="card"><div className="section-head"><h3>Itens e serviços</h3>{editing&&<span className="edit-pill">EDITÁVEL</span>}</div><div className="price-list editable-price-list">{(view.items||[]).map((i,index)=><div key={i.key}><div className="price-service-copy"><span>{i.label}</span><small>{i.durability?`Durabilidade ${i.durability}`:''}{i.durability&&i.max?' · ':''}{i.max?`Máx. ${i.max}`:''}</small></div>{editing?<div className="price-edit-row"><input className="price-input" type="number" min="0" value={i.price} onChange={e=>setNumber(['items',index,'price'],e.target.value)}/><button type="button" className="icon-button danger" onClick={()=>removeService(i.key)} title="Remover serviço"><Trash2 size={16}/></button></div>:<strong>$ {money(i.price)}</strong>}</div>)}<div><span>Guincho</span>{editing?<div className="inline-price-edit"><label>Base<input className="price-input" type="number" value={view.towing?.base||0} onChange={e=>setNumber(['towing','base'],e.target.value)}/></label><label>/ 2 km<input className="price-input" type="number" value={view.towing?.per2Km||0} onChange={e=>setNumber(['towing','per2Km'],e.target.value)}/></label></div>:<strong>$ {money(view.towing?.base)} + $ {money(view.towing?.per2Km)} / 2 km</strong>}</div>{(view.dmv||[]).map((d,index)=><div key={d.key}><span>{d.label}</span>{editing?<input className="price-input" type="number" min="0" value={d.price} onChange={e=>setNumber(['dmv',index,'price'],e.target.value)}/>:<strong>$ {money(d.price)}{d.materials?' + materiais':''}</strong>}</div>)}</div></div><div className="card"><h3>Estética</h3><div className="price-list">{(view.aesthetics||[]).map((i,index)=><div key={i.key}><span>{i.label}</span>{editing?<input className="price-input" type="number" min="0" value={i.price} onChange={e=>setNumber(['aesthetics',index,'price'],e.target.value)}/>:<strong>$ {money(i.price)}</strong>}</div>)}</div></div></div>
  {editing&&<div className="card top-gap"><div className="section-head"><div><span className="eyebrow">NOVO TIPO</span><h3>Adicionar serviço à calculadora</h3></div><Plus size={22}/></div><div className="form-grid four"><div><label>Nome do serviço</label><input value={newService.label} onChange={e=>setNewService({...newService,label:e.target.value})} placeholder="Ex.: Alinhamento especial"/></div><div><label>Valor</label><input type="number" min="0" value={newService.price} onChange={e=>setNewService({...newService,price:e.target.value})} placeholder="0"/></div><div><label>Máximo (opcional)</label><input type="number" min="0" value={newService.max} onChange={e=>setNewService({...newService,max:e.target.value})}/></div><div><label>Durabilidade (opcional)</label><input type="number" min="0" value={newService.durability} onChange={e=>setNewService({...newService,durability:e.target.value})}/></div></div><button type="button" className="button top-gap" onClick={addService}><Plus size={17}/> Adicionar serviço</button></div>}
 </>
}
