import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, CarFront, ChevronDown, ChevronUp, Search, UserRound, Wrench } from 'lucide-react'
import { useUI } from '../../context/UIContext'
import { subscribeClients, subscribeServices } from '../../services/firestore'
const money=v=>Number(v||0).toLocaleString('pt-BR')

export default function ClientsPage(){
 const{toast}=useUI();const[clients,setClients]=useState([]);const[history,setHistory]=useState([]);const[q,setQ]=useState('');const[open,setOpen]=useState(null)
 useEffect(()=>subscribeClients(setClients,(e)=>{console.error(e);toast('Não foi possível carregar os clientes.','error')}),[toast])
 useEffect(()=>subscribeServices(setHistory,(e)=>{console.error(e);toast('Não foi possível carregar os serviços dos clientes.','error')}),[toast])
 const clientRows=useMemo(()=>{const map=new Map(clients.map(c=>[String(c.id),{...c,services:[]}])) ;history.forEach(record=>{const key=String(record.clientId);if(!map.has(key))map.set(key,{id:key,name:record.clientName||'Cliente sem nome salvo',createdAt:null,services:[]});map.get(key).services.push(record)});return [...map.values()].map(c=>({...c,services:c.services.sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0))})).sort((a,b)=>(a.name||'').localeCompare(b.name||'','pt-BR'))},[clients,history])
 const filtered=clientRows.filter(c=>`${c.name} ${c.id}`.toLowerCase().includes(q.toLowerCase()))
 return <><div className="page-heading"><div><span className="eyebrow">ADMINISTRAÇÃO</span><h1>Clientes</h1><p>Lista de clientes cadastrados e histórico completo dos serviços solicitados por cada um.</p></div></div><div className="searchbar"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar cliente por nome ou ID..."/></div>{filtered.length===0?<div className="card empty-state large">Nenhum cliente cadastrado.</div>:<div className="client-list">{filtered.map(client=>{const expanded=open===client.id;const total=client.services.reduce((sum,r)=>sum+Number(r.total||0),0);return <article className="card client-card" key={client.id}><button className="client-card-head" onClick={()=>setOpen(expanded?null:client.id)}><div className="client-identity"><div className="avatar small">{client.name?.charAt(0)}</div><div><strong>{client.name}</strong><span>ID #{client.id}</span></div></div><div className="client-stats"><div><span>SERVIÇOS</span><strong>{client.services.length}</strong></div><div><span>TOTAL</span><strong>$ {money(total)}</strong></div>{expanded?<ChevronUp/>:<ChevronDown/>}</div></button>{expanded&&<div className="client-services">{client.services.length===0?<div className="empty-state">Este cliente ainda não possui serviços finalizados.</div>:client.services.map(record=><div className="client-service" key={record.id}><div className="client-service-top"><div><span className="record-code">SERVIÇO</span><strong>$ {money(record.total)}</strong></div><span><CalendarDays size={14}/>{record.createdAt?new Date(record.createdAt).toLocaleString('pt-BR'):'Agora'}</span></div><div className="history-meta compact"><span><UserRound size={15}/>{record.mechanic?.name} · ID {record.mechanic?.id}</span><span><Wrench size={15}/>{record.mechanic?.role}</span></div><div className="client-service-body"><div className="mod-list">{(record.modifications||[]).map((m,i)=><div key={i}><span>{m.label}</span><strong>$ {money(m.price)}</strong></div>)}</div><div className="client-service-images">{record.vtuningImage&&<figure><img src={record.vtuningImage} alt="V-Tuning"/><figcaption>V-Tuning</figcaption></figure>}{record.vehicleImage&&<figure><img src={record.vehicleImage} alt="Veículo"/><figcaption><CarFront size={13}/> Veículo</figcaption></figure>}</div></div></div>)}</div>}</article>})}</div>}</>
}
